version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /packages/cli
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /packages/compify-pack
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /packages/templates/dark-solar-saas
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
